const fs = require('fs');
const path = require('path');
const {spawn} = require('child_process');
const os = require('os');
const assert = require('assert');
const nodeModules = process.env.CODEX_NODE_MODULES || path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const {chromium} = require(path.join(nodeModules, 'playwright'));
const app = path.resolve(__dirname, '..');
const out = path.join(__dirname, 'artifacts');
fs.mkdirSync(out, {recursive:true});
const data = fs.mkdtempSync(path.join(out, 'browser-data-'));
const python = process.env.FOOD_CLASSIFIER_PYTHON || path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe');
const port = 18011;
const base = `http://127.0.0.1:${port}`;
const service = spawn(python, ['-X','utf8',path.join(app,'server.py'),'--port',String(port),'--data-dir',data],{cwd:app,windowsHide:true,stdio:['ignore','pipe','pipe']});
let logs = '', browser;
service.stdout.on('data',d=>logs+=d.toString()); service.stderr.on('data',d=>logs+=d.toString());
const report={checks:[],consoleErrors:[],screenshots:[],startedAt:new Date().toISOString()};
function checked(name) { report.checks.push(name); console.log('PASS',name); }
async function screenshot(page,name,fullPage=false) { const file=path.join(out,name+'.png');await page.screenshot({path:file,fullPage});report.screenshots.push(file); }
(async()=>{
  try {
    let ready=false;
    for(let i=0;i<50;i++){
      try {const r=await fetch(base+'/api/health');if(r.ok){ready=true;break;}}catch{}
      await new Promise(resolve=>setTimeout(resolve,200));
    }
    assert(ready,'local test service failed to start: '+logs);
    browser=await chromium.launch({headless:true,executablePath:process.env.EDGE_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
    const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true,locale:'zh-CN'});
    const page=await context.newPage();
    page.on('pageerror',e=>report.consoleErrors.push(e.message));
    await page.goto(base);
    await page.waitForFunction(()=>document.querySelector('#stat-foods').textContent==='272');
    await screenshot(page,'01-首页');checked('首页资料覆盖数字来自后端');
    await page.locator('.sample[data-food="苹果"]').click();
    await page.locator('.result-summary').waitFor();
    assert((await page.locator('.result-summary').innerText()).includes('仁果类水果'));
    assert.strictEqual(await page.locator('.taxonomy-card').count(),9);
    await screenshot(page,'02-苹果分类',true);checked('苹果分类、独立的 9 套国标分类体系');
    await page.locator('.result-summary [data-evidence]').click();
    await page.locator('#source-preview:not([hidden])').waitFor({timeout:20000});
    assert((await page.locator('#evidence-content').innerText()).includes('382'));
    await screenshot(page,'03-分类原文');checked('分类依据原文页图像可见，页码正确');
    await page.locator('#evidence-dialog .close-dialog').click();
    await page.locator('[data-tab="items"]').click();
    assert.strictEqual(await page.locator('#result-panel tbody tr').count(),5);checked('苹果 5 项检验依据与方法逐行显示');
    await page.locator('[data-tab="standards"]').click();
    await page.locator('#standard-search').fill('23200.113');
    await page.locator('[data-standard]').first().click();
    await page.locator('#standard-content .dialog-body').waitFor();
    assert((await page.locator('#standard-content').innerText()).includes('正文中的引用'));
    await screenshot(page,'04-标准详情与引用');checked('标准范围、版本和间接引用可以展开');
    await page.locator('#standard-dialog .close-dialog').click();
    await page.locator('#standard-search').fill('');
    await page.locator('[data-filter="missing"]').click();
    assert(await page.locator('.file-card').count()>0);
    assert((await page.locator('#standard-list').innerText()).includes('缺正式原文'));checked('缺失原文单独展示');
    await page.locator('.sample[data-food="小麦粉"]').click();
    await page.locator('.result-head h2').filter({hasText:'小麦粉'}).waitFor();
    await page.locator('[data-tab="standards"]').click();
    const downloadPromise=page.waitForEvent('download');
    await page.locator('#bundle-link').click();
    const download=await downloadPromise;
    const downloadPath=await download.path();
    assert(fs.statSync(downloadPath).size>10000);
    assert(download.suggestedFilename().endsWith('.zip'));
    checked('浏览器可以下载包含国标原文的 ZIP 包');
    await screenshot(page,'05-关联国标',true);
    await page.locator('[data-tab="review"]').click();
    await page.locator('#review-actor').fill('浏览器验收');
    await page.locator('#review-action').selectOption({label:'补充资料'});
    await page.locator('#review-note').fill('确认通用或专用小麦粉，需核对标签和用途。');
    await page.locator('#review-form button[type="submit"]').click();
    await page.locator('.review-log').waitFor();checked('人工处理人、时间、动作及依据保存');
    await page.locator('.nav[data-view="history"]').click();
    await page.locator('.history-row').first().waitFor();
    await page.locator('.history-row').first().locator('button').click();
    await page.locator('[data-tab="review"]').click();
    assert((await page.locator('.review-log').innerText()).includes('浏览器验收'));checked('历史查询可恢复处理记录与原始结果');
    await page.locator('#food-input').fill('牛奶');
    await page.locator('#process').selectOption('');
    await page.locator('#search-button').click();
    await page.locator('.candidate-grid').waitFor();
    assert.strictEqual(await page.locator('.result-summary').count(),0);
    await screenshot(page,'06-歧义分类');
    await page.locator('.candidate').filter({hasText:'巴氏杀菌乳'}).click();
    await page.locator('.result-summary').waitFor();
    assert((await page.locator('.result-head').innerText()).includes('用户选择'));checked('牛奶提示歧义，用户可选择具体类型');
    await page.locator('#food-input').fill('<img src=x onerror=alert(1)>');
    await page.locator('#search-button').click();
    await page.locator('.empty-state').waitFor();
    assert.strictEqual(await page.locator('.result-head img').count(),0);checked('未知食品不强行分类，输入按文本安全显示');
    await page.locator('.nav[data-view="catalog"]').click();
    await page.locator('.catalog-item').first().waitFor();
    await page.locator('#catalog-search').fill('蜂蜜');
    await page.locator('.catalog-item').first().click();
    await page.locator('.result-summary').waitFor();
    assert((await page.locator('.result-summary').innerText()).includes('蜂蜜'));checked('目录可以反向选择食品并展开国标关联');
    await page.locator('.nav[data-view="definitions"]').click();
    await page.locator('#definition-list .definition-card').first().waitFor();
    assert.strictEqual(await page.locator('#definition-list>.definition-card').count(),102);
    await page.locator('#definition-search').fill('专用小麦粉');
    assert.strictEqual(await page.locator('#definition-list>.definition-card').count(),1);
    await page.locator('#definition-list>.definition-card>summary').click();
    assert((await page.locator('#definition-list').innerText()).includes('全麦粉'));
    await screenshot(page,'10-产品种类定义库',true);checked('102 个分节定义可以全文检索并展开完整原句');
    await page.locator('#definition-list .definition-paragraph [data-evidence]').first().click();
    await page.locator('#source-preview:not([hidden])').waitFor();
    assert((await page.locator('#evidence-content').innerText()).includes('PDF 第 5 页'));
    await page.locator('#evidence-dialog .close-dialog').click();checked('小麦粉产品种类定位到 PDF 第 5 页并显示原图');
    await page.locator('.nav[data-view="search"]').click();
    await page.locator('#food-input').fill('全麦粉');
    await page.locator('#search-button').click();
    await page.locator('.definition-hit').waitFor();
    assert((await page.locator('.definition-hit').innerText()).includes('小麦粉 → 通用小麦粉 → 全麦粉'));
    assert.strictEqual(await page.locator('.candidate').count(),0);
    await page.locator('#result-panel>.definition-card').waitFor();
    assert((await page.locator('#result-panel>.definition-card').innerText()).includes('原料与加工方式'));
    assert((await page.locator('[data-tab="items"]').innerText()).includes('9'));
    await screenshot(page,'11-全麦粉定义与归类',true);checked('全麦粉自动关联小麦粉项目表，无需点选上级');
    await page.locator('#food-input').fill('黑米');
    await page.locator('#search-button').click();
    await page.locator('.result-head h2').filter({hasText:'黑米'}).waitFor();
    assert((await page.locator('#result-panel').innerText()).includes('不包括黑米'));
    assert((await page.locator('.result-summary').innerText()).includes('谷物加工品'));checked('黑米展示大米排除依据并自动关联谷物加工品');
    await page.locator('#food-input').fill('白虾');
    await page.locator('#process').selectOption('fresh');
    await page.locator('#search-button').click();
    await page.locator('.result-head h2').filter({hasText:'白虾'}).waitFor();
    assert.strictEqual(await page.locator('.candidate').count(),2);
    assert.strictEqual(await page.locator('.result-summary').count(),0);checked('白虾保留淡水与海水双候选');
    await page.locator('[data-tab="items"]').click();
    assert((await page.locator('[data-tab="items"]').innerText()).includes('按分支'));
    assert.strictEqual(await page.locator('.inspection-option').count(),2);
    const freshShrimp=page.locator('.inspection-option').filter({hasText:'淡水虾'});
    await freshShrimp.locator('[data-preview-items]').click();
    await freshShrimp.locator('tbody tr').first().waitFor();
    assert.strictEqual(await freshShrimp.locator('tbody tr').count(),11);
    await screenshot(page,'13-多分支项目预览',true);checked('白虾不显示零项，可直接展开淡水虾 11 项而不强制归类');
    await page.locator('#food-input').fill('年糕');
    await page.locator('#process').selectOption('');
    await page.locator('#search-button').click();
    await page.locator('.result-head h2').filter({hasText:'年糕'}).waitFor();
    assert((await page.locator('.result-summary').innerText()).includes('米粉制品'));
    assert((await page.locator('[data-tab="items"]').innerText()).includes('8'));
    await page.locator('[data-tab="items"]').click();
    assert.strictEqual(await page.locator('#result-panel tbody tr').count(),8);
    assert((await page.locator('.inspection-link').innerText()).includes('其他粮食加工品 → 谷物粉类制成品 → 米粉制品 → 年糕'));
    await page.locator('.inspection-link [data-evidence]').last().click();
    await page.locator('#source-preview:not([hidden])').waitFor();
    assert((await page.locator('#evidence-content').innerText()).includes('PDF 第 17 页'));
    await page.locator('#evidence-dialog .close-dialog').click();
    await screenshot(page,'14-年糕自动关联检验项目',true);checked('年糕直接显示米粉制品 8 项，分类原句和项目表均可追溯');
    await page.locator('[data-tab="standards"]').click();
    await page.locator('.file-card').first().waitFor();
    const cakeDownload=page.waitForEvent('download');await page.locator('#bundle-link').click();
    assert((await cakeDownload).suggestedFilename().startsWith('年糕-'));checked('年糕直接关联国标并可下载以食品名命名的资料包');
    await page.locator('#food-input').fill('谷物粉类制成品');
    await page.locator('#search-button').click();
    await page.locator('.result-head h2').filter({hasText:'谷物粉类制成品'}).waitFor();
    await page.locator('[data-tab="items"]').click();
    assert.strictEqual(await page.locator('.inspection-option').count(),4);
    assert.strictEqual(await page.locator('#result-panel tbody tr').count(),0);checked('中间层仅列所属四个项目分支，不混入其他粮食项目');
    await page.setViewportSize({width:390,height:844});
    await page.goto(base);
    await page.waitForFunction(()=>document.querySelector('#stat-foods').textContent==='272');
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await screenshot(page,'07-手机首页',true);
    await page.locator('.sample[data-food="白萝卜"]').click();
    await page.locator('.result-summary').waitFor();
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await screenshot(page,'08-手机分类',true);checked('手机尺寸首页与查询结果无横向溢出');
    assert.deepStrictEqual(report.consoleErrors,[]);
    checked('全流程无浏览器 JavaScript 异常');
    report.success=true;
  } catch (e) {
    report.success=false; report.error=e.stack;
    console.error(e); process.exitCode=1;
  } finally {
    report.finishedAt=new Date().toISOString();
    fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));
    fs.writeFileSync(path.join(out,'test-server.log'),logs);
    if(browser)await browser.close();
    service.kill();
  }
})();
